In [ ]:
1. Write a Python Program to Add Two Matrices?


In [2]:
X = [[2,4,6],
    [2 ,2,2],
    [2 ,4,6]]
 
Y = [[2,4,6],
    [2,2,2],
    [2,4,6]]

result = [[0,0,0],
        [0,0,0],
        [0,0,0]]
 
for i in range(len(X)): # iterate through rows
    for j in range(len(X[0])): #iterate through columns
        result[i][j] = X[i][j] + Y[i][j]
 
for r in result:
    print(r)

[4, 8, 12]
[4, 4, 4]
[4, 8, 12]


In [ ]:
2. Write a Python Program to Multiply Two Matrices?


In [8]:
X = [[2,4,6],
    [2 ,2,2],
    [2 ,4,6]]
 
Y = [[2,4,6],
    [2,2,2],
    [2,4,6]]

result = [[0,0,0],
        [0,0,0],
        [0,0,0]]

import numpy as np

result = np.dot(X,Y)
print(result)

[[24 40 56]
 [12 20 28]
 [24 40 56]]


In [9]:
X = [[2,4,6],
    [2 ,2,2],
    [2 ,4,6]]
 
Y = [[2,4,6],
    [2,2,2],
    [2,4,6]]

result = [[0,0,0],
        [0,0,0],
        [0,0,0]]
 
for i in range(len(X)): #iterating by row of X
    
    for j in range(len(X[0])): #iterating by column of Y
        
        for u in range(len(Y)):#iterating by row of Y
            
            result[i][j]+= X[i][u] * Y[u][j]
 
for r in result:
    print(r)

[24, 40, 56]
[12, 20, 28]
[24, 40, 56]


In [ ]:
3. Write a Python Program to Transpose a Matrix?


In [17]:
A = [ [1, 1, 1],
 [2, 2, 2],
 [3, 3, 3]]

B= [[0,0,0],
    [0,0,0],
    [0,0,0]]
N=3 
for i in range(N):
      for j in range(N):
           B[i][j] = A[j][i]
for b in B:
    print(b)
 

[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


In [ ]:
4. Write a Python Program to Sort Words in Alphabetic Order?


In [26]:
x=input("enter a word:")
print(sorted(x))
print("".join(sorted(x)))

enter a word: Dilpreet


['D', 'e', 'e', 'i', 'l', 'p', 'r', 't']
Deeilprt


In [ ]:
5. Write a Python Program to Remove Punctuation From a String?

In [ ]:
import string

a=str(input("ENTER THE STRING"))

for char in string.punctuation:
    a = a.replace(char, ' ')

print(a)


In [ ]:
;